### ISSUE TITLE
Unexpected end of Json input error on script run

### ISSUE THREAD

**Issue by NeversSync** [Sweets/sndcld-dl#4]

**Comment by Sweets** [comment]
Should be good now, it was for the songs I tested. Let me know.

**Comment by NeversSync** [comment]
Sweet thank you. Are you able to download 320kbps or original upload quality tracks?

**Comment by Sweets** [comment]
Likely not, whatever audio file SoundCloud provides to the front-end user is what is downloaded here, since this takes advantage of some URL forgery magic due to an oversight in the SoundCloud front-end. I also doubt that SoundCloud stores original quality tracks to begin with because it's just not feasible for a site that is known to have a very hard time keeping themselves afloat to have enough storage for original quality tracks given the sheer amount of people that have uploaded and have the ability to upload.

**Comment by NeversSync** [comment]
Yeah, that's what I was thinking, thank you for the clarification and work!

Nicky Evers - Web { Developer | Designer }
https://nickyevers.com/

**Comment by megalon** [comment]
I am also having this same error now, months later.
I've created a simple Node.js project using your example code in the readme, like this 
```
let sndcld_dl = require("./sndcld-dl");

sndcld_dl("https://soundcloud.com/iameden/r-r", "/tmp/eden.mp3");
```

Here is the output
```
PS D:\megalon-github\scdownload-test> node .
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request.track_url_callback [as _callback] (D:\megalon-github\scdownload-test\sndcld-dl.js:19:23)
    at Request.self.callback (D:\megalon-github\scdownload-test\node_modules\request\request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (D:\megalon-github\scdownload-test\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (D:\megalon-github\scdownload-test\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
PS D:\megalon-github\scdownload-test>
```

**Comment by megalon** [comment]
After doing some more testing, my Client ID was the problem.
Everything works fine now

**Comment by Sweets** [comment]
@megalon The client ID seems to change every so often due to SoundCloud updating their own service. It happens somewhat often -- I may end up writing some code up that enables sndcld_dl to just find the current client ID that SoundCloud uses on their site to prevent this from happening again.
